In [1]:
import numpy as np

In [3]:
# Sigmoid Activation Function

def sigmoid(x):
    return 1 / (1 + np.exp(-x)) # Sigmoid function maps any real-valued number into the (0, 1) interval, making it useful for binary classification problems.

# Derivative of Sigmoid Function

def sigmoid_derivative(x):
    return x * (1 - x) # The derivative of the sigmoid function can be expressed in terms of the output of the sigmoid function itself, which simplifies calculations during backpropagation in neural networks.

In [4]:
# Input dataset

X = np.array([[1, 0, 1]])

# Expected output

y = np.array([[1]])

print("Input:")
print(X)

print("\nExpected Output:")
print(y)

Input:
[[1 0 1]]

Expected Output:
[[1]]


In [6]:
# Initialize random weights

np.random.seed(1)

# Input layer to hidden layer weights
weights_input_hidden = np.random.rand(3, 3)

# Hidden layer to output layer weights
weights_hidden_output = np.random.rand(3, 1)

# Biases
bias_hidden = np.random.rand(1, 3)
bias_output = np.random.rand(1, 1)

print("Initial Weights:")
print("Weights from Input to Hidden Layer:")
print(weights_input_hidden)
print("Weights from Hidden to Output Layer:")
print(weights_hidden_output)

Initial Weights:
Weights from Input to Hidden Layer:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
Weights from Hidden to Output Layer:
[[0.53881673]
 [0.41919451]
 [0.6852195 ]]


In [ ]:
# Forward Propagation

# Hidden layer calculations
hidden_input = np.dot(X, weights_input_hidden) + bias_hidden # The input to the hidden layer is calculated by taking the dot product of the input data and the weights from the input layer to the hidden layer, and then adding the bias for the hidden layer.

hidden_output = sigmoid(hidden_input) # The output of the hidden layer is calculated by applying the sigmoid activation function to the hidden layer input, which gives us a value between 0 and 1 for each neuron in the hidden layer.

# Output layer calculations
final_input = np.dot(hidden_output, weights_hidden_output) + bias_output # The input to the output layer is calculated by taking the dot product of the hidden layer output and the weights from the hidden layer to the output layer, and then adding the bias for the output layer.

final_output = sigmoid(final_input) # The final output is calculated by taking the dot product of the hidden layer output and the weights from the hidden layer to the output layer, adding the bias for the output layer, and then applying the sigmoid activation function to get a value between 0 and 1.

print("Output after Forward Propagation:")
print(final_output)

Output after Forward Propagation:
[[0.86105179]]


In [ ]:
# Back Propagation

# Calculate error
error = y - final_output

print("Error:")
print(error)

# Calculate gradients for output layer
d_output = error * sigmoid_derivative(final_output) # The gradient for the output layer is calculated by multiplying the error with the derivative of the sigmoid function applied to the final output. This gives us the direction and magnitude of the adjustments needed for the weights between the hidden layer and the output layer.

# Calculate error for hidden layer
hidden_error = d_output.dot(weights_hidden_output.T) # The error for the hidden layer is calculated by taking the dot product of the output layer gradients (d_output) and the transpose of the weights from the hidden layer to the output layer. This backpropagates the error from the output layer to the hidden layer, allowing us to calculate the necessary adjustments for the weights between the input layer and the hidden layer.

# Hidden layer gradients
d_hidden = hidden_error * sigmoid_derivative(hidden_output) # The gradient for the hidden layer is calculated by multiplying the hidden layer error with the derivative of the sigmoid function applied to the hidden layer output. This gives us the direction and magnitude of the adjustments needed for the weights between the input layer and the hidden layer.

# Learning rate
learning_rate = 0.1

# Update hidden-output weights
weights_hidden_output += hidden_output.T.dot(d_output) * learning_rate # The weights between the hidden layer and the output layer are updated by taking the dot product of the transpose of the hidden layer output and the output layer gradients (d_output), and then multiplying by the learning rate. This adjusts the weights in the direction that minimizes the error.

# Update input-hidden weights
weights_input_hidden += X.T.dot(d_hidden) * learning_rate # The weights between the input layer and the hidden layer are updated by taking the dot product of the transpose of the input data (X) and the hidden layer gradients (d_hidden), and then multiplying by the learning rate. This adjusts the weights in the direction that minimizes the error.

print("Weights Updated Successfully")

Error:
[[0.13894821]]
Weights Updated Successfully


In [ ]:
# Training the network

for epoch in range(1000):
    
    # Forward propagation
    
    hidden_input = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_output) + bias_output
    final_output = sigmoid(final_input)

    # Error calculation
    
    error = y - final_output

    # Back propagation
    
    d_output = error * sigmoid_derivative(final_output) # The gradient for the output layer is calculated by multiplying the error with the derivative of the sigmoid function applied to the final output. This gives us the direction and magnitude of the adjustments needed for the weights between the hidden layer and the output layer.

    hidden_error = d_output.dot(weights_hidden_output.T) # The error for the hidden layer is calculated by taking the dot product of the output layer gradients (d_output) and the transpose of the weights from the hidden layer to the output layer. This backpropagates the error from the output layer to the hidden layer, allowing us to calculate the necessary adjustments for the weights between the input layer and the hidden layer.

    d_hidden = hidden_error * sigmoid_derivative(hidden_output) # The gradient for the hidden layer is calculated by multiplying the hidden layer error with the derivative of the sigmoid function applied to the hidden layer output. This gives us the direction and magnitude of the adjustments needed for the weights between the input layer and the hidden layer.

    # Update weights
    
    weights_hidden_output += hidden_output.T.dot(d_output) * learning_rate # The weights between the hidden layer and the output layer are updated by taking the dot product of the transpose of the hidden layer output and the output layer gradients (d_output), and then multiplying by the learning rate. This adjusts the weights in the direction that minimizes the error.
    weights_input_hidden += X.T.dot(d_hidden) * learning_rate # The weights between the input layer and the hidden layer are updated by taking the dot product of the transpose of the input data (X) and the hidden layer gradients (d_hidden), and then multiplying by the learning rate. This adjusts the weights in the direction that minimizes the error.

print("Training Completed")

Training Completed


In [ ]:
# Final output after training

hidden_input = np.dot(X, weights_input_hidden) + bias_hidden # The input to the hidden layer is calculated by taking the dot product of the input data and the weights from the input layer to the hidden layer, and then adding the bias for the hidden layer.

hidden_output = sigmoid(hidden_input) # The output of the hidden layer is calculated by applying the sigmoid activation function to the hidden layer input, which gives us a value between 0 and 1 for each neuron in the hidden layer.

final_input = np.dot(hidden_output, weights_hidden_output) + bias_output # The input to the output layer is calculated by taking the dot product of the hidden layer output and the weights from the hidden layer to the output layer, and then adding the bias for the output layer.

final_output = sigmoid(final_input)

print("Final Predicted Output:")
print(final_output)

# Convert into binary output

if final_output >= 0.5:
    print("\nOutput: 1")
else:
    print("\nOutput: 0")

Final Predicted Output:
[[0.94791811]]

Output: 1
