In [1]:
import numpy as np

In [2]:
# Input patterns (Set A)

X1 = np.array([[1], [1], [1]])
X2 = np.array([[-1], [-1], [-1]])

# Target patterns (Set B)

Y1 = np.array([[1], [1], [1], [1], [1], [1]])
Y2 = np.array([[-1], [-1], [-1], [-1], [-1], [-1]])

print("Input Pattern X1:")
print(X1)

print("\nTarget Pattern Y1:")
print(Y1)

print("\nInput Pattern X2:")
print(X2)

print("\nTarget Pattern Y2:")
print(Y2)

Input Pattern X1:
[[1]
 [1]
 [1]]

Target Pattern Y1:
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]

Input Pattern X2:
[[-1]
 [-1]
 [-1]]

Target Pattern Y2:
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]


In [3]:
# Weight matrix calculation

W1 = np.dot(X1, Y1.T)
W2 = np.dot(X2, Y2.T)

# Final BAM Weight Matrix

W = W1 + W2

print("Weight Matrix:")
print(W)

Weight Matrix:
[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


In [4]:
# Activation Function

def activation(x):
    
    return np.where(x >= 0, 1, -1)

In [ ]:
# Testing Input Pattern 1

print("Testing for Input Pattern 1")

X_test = X1

# Forward pass
Y_in = np.dot(W.T, X_test) # Calculate the input to the output layer

Y_out = activation(Y_in) # Apply activation function to get the output pattern

print("Output:")
print(Y_out)

Testing for Input Pattern 1
Output:
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [ ]:
# Testing Input Pattern 2

print("Testing for Input Pattern 2")

X_test = X2

# Forward pass
Y_in = np.dot(W.T, X_test) # Calculate the input to the output layer

Y_out = activation(Y_in) # Apply activation function to get the output pattern

print("Output:")
print(Y_out)

Testing for Input Pattern 2
Output:
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]


In [7]:
# Testing Noisy Input Pattern 3

X3 = np.array([[1], [-1], [1]])

print("Testing for Input Pattern 3")

Y_in = np.dot(W.T, X3)

Y_out = activation(Y_in)

print("Output:")
print(Y_out)

Testing for Input Pattern 3
Output:
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [8]:
# Testing Noisy Input Pattern 4

X4 = np.array([[-1], [1], [-1]])

print("Testing for Input Pattern 4")

Y_in = np.dot(W.T, X4)

Y_out = activation(Y_in)

print("Output:")
print(Y_out)

Testing for Input Pattern 4
Output:
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]
