In [1]:
import numpy as np

In [2]:
# Define 4 bipolar vectors

pattern1 = np.array([1, 1, -1, -1])
pattern2 = np.array([-1, 1, -1, 1])
pattern3 = np.array([1, -1, 1, -1])
pattern4 = np.array([-1, -1, 1, 1])

# Store all patterns

patterns = np.array([
    pattern1,
    pattern2,
    pattern3,
    pattern4
])

print("Training Patterns:")
print(patterns)

Training Patterns:
[[ 1  1 -1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]
 [-1 -1  1  1]]


In [3]:
# Number of neurons

n = patterns.shape[1]

# Initialize weight matrix with zeros

W = np.zeros((n, n))

print("Initial Weight Matrix:")
print(W)

Initial Weight Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# Training using Hebbian Learning Rule

for pattern in patterns:
    
    pattern = pattern.reshape(n, 1)
    
    W += np.dot(pattern, pattern.T)

# Remove self-connections

np.fill_diagonal(W, 0)

print("Final Weight Matrix:")
print(W)

Final Weight Matrix:
[[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]


In [5]:
# Activation Function

def activation(x):
    
    if x >= 0:
        return 1
    else:
        return -1

In [6]:
# Test input pattern (noisy input)

test_pattern = np.array([1, 1, -1, 1])

print("Test Pattern:")
print(test_pattern)

Test Pattern:
[ 1  1 -1  1]


In [7]:
# Recall process

output = test_pattern.copy()

for i in range(n):
    
    net_input = np.dot(W[i], output)
    
    output[i] = activation(net_input)

print("Recovered Pattern:")
print(output)

Recovered Pattern:
[-1  1 -1  1]


In [8]:
print("Stored Patterns:")

for i in range(len(patterns)):
    
    print("Pattern", i+1)
    print(patterns[i])

Stored Patterns:
Pattern 1
[ 1  1 -1 -1]
Pattern 2
[-1  1 -1  1]
Pattern 3
[ 1 -1  1 -1]
Pattern 4
[-1 -1  1  1]
